### ISSUE TITLE
Python library to simplify the interaction with dim

### ISSUE THREAD

**Issue by lisphilar** [c-3lab/dim#82]
Thank you for creating this project :)
Data installation manager is absolutely required for open source community. I faced some difficulties when developing a dataset and a data analysis tool with Python regarding COVID-19.

Is it possible to add Python (+R?) library to simplify the interaction with dim?
(I'm not sure we can call Deno from Python...)
Users may use the new library as follows.

1. Install the library, like `poetry add dim-python`
2. Write settings on "pyproject.toml" with commands. This TOML format file is the standard Python library management file currently.

```Toml
[tool.dim]
directory = './data_files'
datasets = [
    {
        name = 'example',
        url = 'https://example.com',
        unzip = true,
        forced = true,
        encoding = 'utf-8',
        postprocess = ["poetry run python ./tests/test_custom_command.py",],
    },
]
```

3. Update datasets with `poetry run dim update`, or

4. Update/load the dataset with Python scripts.
```Python
import dim
dim.config(settings='./data_files/dim-lock.json')
data = dim.load(name='example')
```

I'm just a new user, but very interested in this project.
